version: "3.7"

services:
    sample-prod:
        container_name: sapo-alimenticio-prod
        build:
            context: .
            dockerfile: Dockerfile.prod
        ports:
            - "1337:80"
